### ISSUE TITLE
friction getting good canonical URLs

### ISSUE THREAD

**Issue by james-baker** [buttondown-email/roadmap#918]
After I send a newsletter, I want the canonical pretty URL to post/share, and some recent changes have made that harder. (And I don't need or use custom slugs, so that's not relevant here.)

This shows up a couple of ways.

One raw-id-looking form shows up in the post-publish dialog:
![image](https://user-images.githubusercontent.com/89615/201448608-a668ba71-3cf2-44cf-aaee-0903d5f29845.png)
If this URL updated to the pretty one after the emails sent (for whatever technical debt reason), that'd be okay and I'd wait a minute to get the nice one. But the dialog never updates, and the "Copy URL to clipboard" button also uses that ugly guid.

So, then I click back to my list of emails, then get the URL from the "View" item-context-menu option. Then, sometimes, the second form of ugly URLs shows up: a 4-digit number tacked on the end of the slug. I haven't figured out why/when this happens only sometimes.
![image](https://user-images.githubusercontent.com/89615/201449313-f946e91e-f8b6-4a6e-a99c-09e256267dbf.png)
If I delete the last dash-and-4-digits... the page still loads fine with the expected pretty url. I don't have any name conflicts that would necessitate numbering otherwise-identical slugs. I'm not sure why the 4 digits are there.

Sometimes... and I'm not too sure... sometimes the 4 digits are there initially, but not in the slug that Buttondown keeps around permanently? There are a few in my archive that Buttondown's "View" keeps them around, yet I think there used to be more and some of them disappeared.

Anyway, in sum:
Expected: final normal/default/pretty slug URL is the only URL I ever see
Actual: there are two other uglier URL types that show up, adding friction to my workflow while not actually blocking the functioning of the normal URLs/slugs

**Comment by james-baker** [comment]
I noticed this on my next email: I started by reusing another email (not sure if that's relevant) and when I checked the "customize archive" dialog I noticed it had a slug in it, WITH the random 4 digits appended. I deleted the slug and saved. When I sent the email, the post-publish dialog showed me the slug-with-random-4-digits. That's at least better than the naked guid, but it's still not what I would expect after manually deleting that slug pre-publishing.

I've also verified that the good URL *does* work immediately, even before the emails get sent out... which makes it seem like there's no big technical reason to have other URL forms show up.

**Comment by jmduke** [comment]
Teasing out a couple things here, since I think they're technically separate bugs that all appear in the same part of the flow:

> Sometimes... and I'm not too sure... sometimes the 4 digits are there initially, but not in the slug that Buttondown keeps around permanently? There are a few in my archive that Buttondown's "View" keeps them around, yet I think there used to be more and some of them disappeared.

_This_ should be fixed as of now. (What was happening at a high level: Buttondown set a slug of `nice-slug`, then would _reset_ a second slug because it thought the extant slug of `nice-slug` was present on a second email.)

> One raw-id-looking form shows up in the post-publish dialog

I think this is a net-new bug (to me) that I'll chase down. (That absolute URL should only appear when there's no slug set for the email, which sounds like it might be a weird race condition or something here.)

> When I sent the email, the post-publish dialog showed me the slug-with-random-4-digits. That's at least better than the naked guid, but it's still not what I would expect after manually deleting that slug pre-publishing

This is 'intended behavior' (Buttondown interprets the empty slug as 'no change here'), but agree that it's not ideal. Will change.

**Comment by james-baker** [comment]
Thanks for the first, I'll keep an eye out.

Re the absolute URL bug, yup still seeing it. Really jars the flow of sharing what one just published.
Maybe the nice-slug field starts out empty, and the "show the link in the post-publish dialog" code runs before the "make a nice-slug if nice-slug is empty" code?

**Comment by james-baker** [comment]
Just noting that this (the ugly GUID url being shown in the post-publish dialog) repros 100% of the time for me. If this is the case for everyone, it'd seem pretty high priority. I've learned to just close the post-publish dialog, go back to my list of emails, and copy the correct URL from the "view" link in the email's context menu.

**Comment by jmduke** [comment]
+1: agreed. Sorry, this one got away from me; throwing a priority label on it.

**Comment by james-baker** [comment]
Confirmed. Reproduced the bug today, then did a hard refresh to get the new code, then observed the correct behavior. 👍🏻

**Comment by jmduke** [comment]
@james-baker thanks for the confirmation (and the patience!)
